 image: docker:stable

 before_script:
   - docker info

 stages:
   - build

 build:
   stage: build
   script:
     - docker build -t avr-rust .

     # <FIXME: move into 'test' stage>
     # Clone source code of the blink repository.
     - docker run -v $(pwd):/hostpwd -w /hostpwd avr-rust git clone https://github.com/avr-rust/blink.git
     # Compile the blink example in release mode.
     - docker run -v $(pwd)/blink:/blink-src -e RUST_TARGET_PATH=/blink-src -w /blink-src avr-rust xargo build --target avr-atmega328p --release
     # </FIXME: move into 'test' stage>

